### ISSUE TITLE
Import external modules

### ISSUE THREAD

**Issue by janbaer** [zewa666/angular_es6#1]
How can I import external modules that I have to define in 

```
angular.module('MyApp', ['ngMaterial']);
```

even when I import the module before with

```
import {ngMaterial} from 'angular-material'
```

It'll not work. I installed the module before with **jspm install --save**

**Comment by zewa666** [comment]
Hi there,

so the way you'd go here is following:

## Install angular-material

`jspm install angular-material`

This will install the bower package of Angular-Material into the JSPM_Packages folder

## Import the module

To do so, at the top of the file put in this code

```
import ngMaterial from 'angular-material';
```

Note the module definition without curly braces {}
This is because the included module is not an ES6-Module but rather based on CommonJS standard. To verify that look into the file `jspm_packages/angular/bower-material@YOURVERSION.js`
In there you see something like this:

```
module.exports = require("github:angular/bower-material@0.8.2/angular-material");
```

So in order to work, just import it without curly braces

## Add Angular dependency

Finally as you already stated just add the angular dependency to your module like this:

```
var app = angular.module('AngularES6', ['ngMaterial']);
```

## Example

Now I haven't really worked with ngMaterial, but I tried out the sidebar stuff, so here is my modified index.html

``` html
...
<body ng-app="AngularES6">
    <div class="container" ng-controller="MainCtrl as ctrl">
      <md-toolbar>
        <h1>Flickr Photo Album</h1>
      </md-toolbar>
      <button ng-click="ctrl.toggleSideBar()">Toggle</button>
      <md-sidenav layout="column" class="md-sidenav-left md-whiteframe-z2" md-component-id="left" md-is-locked-open="$media('gt-sm')">
        Hello
      </md-sidenav>
...
```

and here the new mainctrl.js

```
export class MainCtrl {
  constructor($scope, FlickrService, $mdSidenav) {
    this.images = [];
    this.searchTag = "AngularJS";
    this.service = FlickrService;
    this.$mdSidenav = $mdSidenav;
  }

  toggleSideBar() {
    this.$mdSidenav('left').toggle();
  }
}
```

note here that since we're using ES6 you can leverage this nice form to define methods, as such you need to put `$mdSidenav` into a class property inside the constructor.

BTW. I see you're from Munich. I'll be in Nurnberg at the DWX Conference as a speaker regarding exactly the stuff shown here in the repo http://www.developer-week.de/Programm/Veranstaltung/(event)/19008. See you there maybe :)

**Comment by janbaer** [comment]
Thanks for your detailed answer. In my case it was also enough to just import ngMaterial with

```
import 'angular-material';
```

I'll mark this appointment in my calendar. Maybe I'll be there!
